// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD123gSaN6djSoCtQcWJgcZrDEH_v2BqSA',
    appId: '1:880548422681:web:d0162af4fab5e7df1ef688',
    messagingSenderId: '880548422681',
    projectId: 'asa-server-eye',
    authDomain: 'asa-server-eye.firebaseapp.com',
    storageBucket: 'asa-server-eye.firebasestorage.app',
    measurementId: 'G-7RHJHSYJ0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ACkdDis8Y0r1BZ4d0LKsj48_7S1FpWE',
    appId: '1:880548422681:android:5a9e1853b9edf4201ef688',
    messagingSenderId: '880548422681',
    projectId: 'asa-server-eye',
    storageBucket: 'asa-server-eye.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChd4bGJmtIo6eTjQfQzzFvSNG6loSv4vQ',
    appId: '1:880548422681:ios:daa437d1ee7f54b81ef688',
    messagingSenderId: '880548422681',
    projectId: 'asa-server-eye',
    storageBucket: 'asa-server-eye.firebasestorage.app',
    iosBundleId: 'com.appakademie.asaservereye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChd4bGJmtIo6eTjQfQzzFvSNG6loSv4vQ',
    appId: '1:880548422681:ios:daa437d1ee7f54b81ef688',
    messagingSenderId: '880548422681',
    projectId: 'asa-server-eye',
    storageBucket: 'asa-server-eye.firebasestorage.app',
    iosBundleId: 'com.appakademie.asaservereye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD123gSaN6djSoCtQcWJgcZrDEH_v2BqSA',
    appId: '1:880548422681:web:043f2a68b489218c1ef688',
    messagingSenderId: '880548422681',
    projectId: 'asa-server-eye',
    authDomain: 'asa-server-eye.firebaseapp.com',
    storageBucket: 'asa-server-eye.firebasestorage.app',
    measurementId: 'G-QF5YXMWWL7',
  );
}
